import { describe, it, expect } from "vitest";
import {
  shouldAutoReply,
  looksAutoGenerated,
  isRobotAddress,
} from "./email-autoreply";

/**
 * These are the guards, and they are the whole reason an email auto-responder
 * is safe to switch on. Two responders pointed at each other send forever; a
 * hole here is an outage and a rate-limited domain, not a cosmetic bug.
 */

const OURS = new Set(["hello@trewellness.in", "doctor@trewellness.in"]);
const headers = (h: Record<string, string> = {}) => new Map<string, unknown>(Object.entries(h));

describe("isRobotAddress", () => {
  it("catches the daemon and no-reply conventions on any domain", () => {
    for (const a of [
      "mailer-daemon@googlemail.com",
      "postmaster@example.org",
      "no-reply@booking.com",
      "noreply@stripe.com",
      "donotreply@bank.in",
      "do-not-reply@airline.com",
      "bounces@sendgrid.net",
    ]) {
      expect(isRobotAddress(a), a).toBe(true);
    }
  });

  it("leaves real people alone", () => {
    for (const a of ["nikkis.siddi@gmail.com", "marc_boesch@tjx.com", "replyto@acme.com"]) {
      expect(isRobotAddress(a), a).toBe(false);
    }
  });

  it("treats a missing address as a robot — never reply into the void", () => {
    expect(isRobotAddress(null)).toBe(true);
    expect(isRobotAddress("")).toBe(true);
  });
});

describe("looksAutoGenerated", () => {
  it("honours RFC 3834 Auto-Submitted", () => {
    expect(looksAutoGenerated(headers({ "auto-submitted": "auto-replied" }))).toBe(true);
    expect(looksAutoGenerated(headers({ "auto-submitted": "auto-generated" }))).toBe(true);
    // "no" is the explicit marker for a human-sent message.
    expect(looksAutoGenerated(headers({ "auto-submitted": "no" }))).toBe(false);
  });

  it("catches bulk mail and mailing lists", () => {
    expect(looksAutoGenerated(headers({ precedence: "bulk" }))).toBe(true);
    expect(looksAutoGenerated(headers({ precedence: "list" }))).toBe(true);
    expect(looksAutoGenerated(headers({ "list-id": "<news.example.com>" }))).toBe(true);
    expect(looksAutoGenerated(headers({ "list-unsubscribe": "<mailto:x@y.z>" }))).toBe(true);
  });

  it("catches the Microsoft and vendor markers", () => {
    expect(looksAutoGenerated(headers({ "x-auto-response-suppress": "All" }))).toBe(true);
    expect(looksAutoGenerated(headers({ "x-autoreply": "yes" }))).toBe(true);
  });

  it("passes an ordinary message through", () => {
    expect(looksAutoGenerated(headers({ subject: "Re: my booking", from: "a@b.c" }))).toBe(false);
    expect(looksAutoGenerated(headers())).toBe(false);
  });
});

describe("shouldAutoReply", () => {
  it("never answers our own address — the loop that would actually happen", () => {
    // 1,240 of this CRM's 1,398 inbound emails are from hello@ because the
    // website form mailer posts as us. Answering those loops on every poll.
    const d = shouldAutoReply({
      fromEmail: "hello@trewellness.in",
      headers: headers(),
      ourAddresses: OURS,
    });
    expect(d.send).toBe(false);
    expect(d.reason).toMatch(/our own/i);
  });

  it("is case-insensitive about our own address", () => {
    expect(
      shouldAutoReply({ fromEmail: "Hello@TreWellness.in", headers: headers(), ourAddresses: OURS }).send,
    ).toBe(false);
  });

  it("never answers a daemon or a machine", () => {
    expect(
      shouldAutoReply({ fromEmail: "mailer-daemon@googlemail.com", headers: headers(), ourAddresses: OURS }).send,
    ).toBe(false);
    expect(
      shouldAutoReply({
        fromEmail: "someone@example.com",
        headers: headers({ "auto-submitted": "auto-replied" }),
        ourAddresses: OURS,
      }).send,
    ).toBe(false);
  });

  it("never answers another address on our own domain", () => {
    // wp@ is the WordPress form mailer — 86 of this CRM's inbound emails —
    // and ma@ is another internal sender. Neither is a guest.
    for (const a of ["wp@trewellness.in", "ma@trewellness.in", "someone@trewellness.in"]) {
      const d = shouldAutoReply({ fromEmail: a, headers: headers(), ourAddresses: OURS });
      expect(d.send, a).toBe(false);
    }
  });

  it("answers a real person writing in", () => {
    const d = shouldAutoReply({
      fromEmail: "nikkis.siddi@gmail.com",
      headers: headers({ subject: "Do you have single occupancy?" }),
      ourAddresses: OURS,
    });
    expect(d.send).toBe(true);
  });

  it("refuses when there is no sender to reply to", () => {
    expect(shouldAutoReply({ fromEmail: null, headers: headers(), ourAddresses: OURS }).send).toBe(false);
  });
});
